version: "3.9"

services:
  django-front:
    build:
      context: ./contexts/django
      dockerfile: Dockerfile-django
    tty: true
    image: django
    container_name: django
    # command: python manage.py runserver 0.0.0.0:8000
    # command: python ./django_app/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./volumes/django/project-dir:/project-dir
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
  # db:
  #   image: postgres
  #   volumes:
  #     - ./volumes/django/data/db:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
